### ISSUE TITLE
show solved problems in contest

### ISSUE THREAD

**Issue by jpswing** [soj-allstars/soj_front-end#12]
implement after the api ready.
https://github.com/soj-allstars/soj/issues/4

**Comment by jpswing** [comment]
比赛详情的api里已经加上了is_solved字段，如果为true就把比赛题目列表里对应的题目做一下标记，比如打个勾或者标绿等等
![image](https://user-images.githubusercontent.com/41479689/81157450-8fa68c80-8fb9-11ea-85ba-70365c435887.png)

**Comment by hatsuroku** [comment]
Deadline: 2020/5/8
